name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Inicializa e atualiza todos os submódulos

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'

    - name: Build site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
    ```

**Explicação das Modificações:**

- **`submodules: recursive`**: Esta opção no passo `actions/checkout` assegura que todos os submódulos, incluindo o tema `til`, sejam inicializados e atualizados durante o processo de checkout.

### 3. Commit e Push das Alterações no Workflow

Após atualizar o arquivo `deploy.yml`, faça commit e push das alterações:

```bash
git add .github/workflows/deploy.yml
git commit -m "Configura GitHub Actions para inicializar submódulos recursivamente"
git push origin main
